final_entities = [
    {'realname': 'Iván Duque Márquez', 'nicknames': ['Titere', 'Porky', 'Señor de los mandados de El Ubérrimo',
                                                     'Mijito', 'Presidente Duque', 'Duque', 'Ivan', 'Ivan Duque Marquez', 'Iván Duque', 'Iván Duque']},
    {'realname': 'Alvaro Uribe', 'nicknames': ['alvaro', 'El innombrable ', 'Patron', 'Presidente Uribe', 'URIBE', 'Álvaro', 'Alvaro Uribe Velez', 'Senador Uribe',
                                               'Alvaro Uribe Vélez', 'Álvaro Uribe', 'Álvaro Uribe Vélez @AlvaroUribeVel', 'Álvaro Uribe Vélez', 'Presidente Uribe', 'Alvaro Uribe', 'PARACO', 'uribe velez']},
    {'realname': 'Pablo Catatumbo', 'nicknames': ['Narcoterrorista']},
    {'realname': 'Antanas Mockus', 'nicknames': ['Profe', 'Mockus']},
    {'realname': 'Juan Manuel Santos ', 'nicknames': ['El culpable', 'Santos', 'sátrapa Santos',
                                                      'Juan Manuel Santos', 'Juan Manuel Santos @JuanManSantos', 'Juan Manuel', 'JuanMa', 'Chuki', 'Juanma', 'JU- HAMPA', 'Falso Nobel', 'presidente Santos', 'JM']},
    {'realname': 'Maria Margarita Zuleta', 'nicknames': ['La paca Zuleta']},
    {'realname': 'Federico Gutiérrez', 'nicknames': [
        'Federico Gutierrez', 'fico', 'fico gutierrez']},
    {'realname': 'Gustavo Petro', 'nicknames': [
        'Gaitanista', 'Gustavo Petro', 'PETRO', 'Petro Summer Camp', 'Terrorista M19', 'Petro', 'petrosky']},
    {'realname': 'Germán Vargas Lleras', 'nicknames': [
        'Frentenacionalista', 'Vargas', 'Lleras', 'vargas lleras']},
    {'realname': 'Humberto de la calle', 'nicknames': [
        'Liberal Reformista', 'De la Calle', 'humberto']},
    {'realname': 'Sergio Fajardo',
        'nicknames': ['Sergio Fajardo', 'Fajardo', 'sergio fajardo valderrama']},
    {'realname': 'María del Rosario Guerra',
        'nicknames': ['Charo Guerra', 'Rosario Guerra']},
    {'realname': 'Daniel Coronell', 'nicknames': [
        'Daniel Coronell', 'Coronell','Daniel Coronel']},
    {'realname': 'César Gaviria', 'nicknames': ['Gaviria', 'cesar gaviria']},
    {'realname': 'Pablo Felipe Robledo',
        'nicknames': ['Felipe Robledo', 'pablo felipe robledo']},
    {'realname': 'Nicolás Maduro',
        'nicknames': ['Maduro', 'Nicolás Maduro']},
    {'realname': 'Juan Guaidó', 'nicknames': [
        'Guaido', 'Presidente Interino de Venezuela', 'Guaidó']},
    {'realname': 'Andrés Felipe Arias Leiva', 'nicknames': [
        'Andresito', 'Arias', 'Andrés Felipe Arias', 'Uribito']},
    {'realname': 'Hugo Rafael Chávez Frías',
        'nicknames': ['Chavez', 'Chávez', 'Hugo Chavez']},
    {'realname': 'Ernesto Macías Tovar', 'nicknames': [
        'Macias', 'Macías', 'Ernesto Macías']},
    {'realname': 'Armando Benedetti',
        'nicknames': ['Armando Benedetti', 'Benedetti']},
    {'realname': 'Daniel Samper Ospina', 'nicknames': ['daniel samper']},
    {'realname': 'Ernesto Samper', 'nicknames': ['samper', 'ernesto samper']},
    {'realname': 'Alejandro Ordóñez', 'nicknames': ['Ordoñez']},
    {'realname': 'Claudia Gurisatti',
        'nicknames': ['La Guri', 'Gurisatti']},
    {'realname': 'Roy Barreras',
        'nicknames': ['Roy', 'Lagarto', 'Roy Barreras']},
    {'realname': 'Guillermo Botero',
        'nicknames': ['Guillermo Botero']},
    {'realname': 'Juanita Goebertus',
        'nicknames': ['Sra Goebertus', 'Juanita Goebertus', 'Goebertus']},
    {'realname': 'Gino Francisco Costa Santolalla',
        'nicknames': ['Gino Costa üáµüá™', 'Gino Costa']},
    {'realname': 'Marco Antonio Arana Zegarra', 'nicknames': [
        'Marco Arana', 'Marco Arana üáµüá™']},
    {'realname': 'Antonio Guerra de la Espriella',
        'nicknames': ['Exsenador Antonio Guerra', 'Antonio Gerra', 'Antonio Guerra']},
    {'realname': 'Yeni Vilcatoma de la Cruz', 'nicknames': ['Yeni Vilcatoma']},
    {'realname': 'Jorge Henrique Simões Barata',
        'nicknames': ['Jorge Barata']},
    {'realname': 'Marcelo Bahia Odebrecht',
        'nicknames': ['Marcelo Odebrecht']},
    {'realname': 'María del Rosario Guerra', 'nicknames': [
        'María del Rosario Guerra', 'Senadora Guerra', 'María del Rosario Guerra de La Espriella']},
    {'realname': 'Rosa María Bartra Barriga', 'nicknames': ['Rosa Bartra']},
    {'realname': 'Marta Peñafiel Portila', 'nicknames': ['martha peñafiel']},
    {'realname': 'Jorge Ramírez Gallego', 'nicknames': ['Jorge Ramírez']},
    {'realname': 'Félix Manuel Moreno Caballero',
        'nicknames': ['Felix Moreno']},
    {'realname': 'Silvana Carrion Ordinola',
        'nicknames': ['Silvana Carrión', 'Silvana Carrion']},
    {'realname': 'Luis Pérez de Acha', 'nicknames': ['Pérez de Acha']},
    {'realname': 'Luisa Maldonado', 'nicknames': ['Luisa Maldonado']},
    {'realname': 'Corte Suprema de Justicia',
        'nicknames': ['Corte Suprema de Jus']},
    {'realname': 'Mávila Milagros Huertas Centurión',
        'nicknames': ['Mavila Huertas C']},
    {'realname': 'Pedro Gonzalo Chávarry Vallejos',
        'nicknames': ['Chávarry']},
    {'realname': 'César José Hinostroza Pariachi',
        'nicknames': ['Hinostroza']},
    {'realname': 'Omar Marcos Arteaga', 'nicknames': ['Omar Marcos']},
    {'realname': 'Martín Alberto Vizcarra Cornejo',
        'nicknames': ['Martín Vizcarra']},
    {'realname': 'Lourdes Luisa Carreño', 'nicknames': [
        'Lourdes Luisa Carreño', 'Lourdes Luisa Carreño carcelen']},
    {'realname': 'Gustavo Gorriti Ellenbogen',
        'nicknames': ['Gustavo Gorriti']},
    {'realname': 'Jorge Enrique Castro Muñoz', 'nicknames': ['Jorge Castro']},
    {'realname': 'Vladimiro Montesinos Torres', 'nicknames': ['Montesinos']},
    {'realname': 'Cesar Epitácio Maia', 'nicknames': ['César Maia']},
    {'realname': 'Rodrigo Felinto Ibarra Epitácio Maia',
        'nicknames': ['Rodrigo Maia']},
    {'realname': 'Keiko Sofía Fujimori Higuchi​',
        'nicknames': ['Keiko Fujimori']},
    {'realname': 'Alberto Kenya Fujimori Fujimori',
        'nicknames': ['A. Fujimori', 'Fujimori']},
    {'realname': 'José Ángel Guerra', 'nicknames': ['Joselito Guerra']},
    {'realname': 'Marta Lucía Ramírez', 'nicknames': [
        'Marta Lucía Ramírez', 'uribista María', 'María', 'Martica', 'Marta Lucia', 'Martha Lucia', 'marta lu', 'martha lu']},
    {'realname': 'Fernando Londoño', 'nicknames': [
        'Fernando Londoño Hoy', 'Fernando Invercolsa Hoyos', 'Fernando Londoño Hoyos', 'Londoño', 'Fernando Londoño', 'Fernando Londoño']},
    {'realname': 'Gustavo Adolfo Rugeles', 'nicknames': [
        'Gustavo Rugeles', 'Maltratador Gustavo Rugeles', 'Rugeles', 'maltratador rugeles']},
    {'realname': 'José Obdulio Gaviria',
        'nicknames': ['Jose Obtuso', 'Obdulio']},
    {'realname': 'Julián Román Rey', 'nicknames': ['Julian Roman']},
    {'realname': 'Aurelio Arturo Martínez', 'nicknames': ['Arturo M.']},
    {'realname': 'Salvatore Mancuso', 'nicknames': [
        'Mancuso', 'salvatore', 'salvatore m', 's mancuso', 'salvatore mancuso']},
    {'realname': 'Carlos Castaño', 'nicknames': [
        'Carlos Castaño', 'carlos castaño', 'castaño']},
    {'realname': 'Jorge Enrique Pizano', 'nicknames': ['Pizano']},
    {'realname': 'Ramiro Bejarano Guzmán',
        'nicknames': ['Ramiro Bejarano Guzmán', 'Ramiro Bejarano']},
    {'realname': 'Mariano Rajoy',
        'nicknames': ['Rajoy', 'Mariano Rajoy']},
    {'realname': 'José Adrián Marrero Berrocal', 'nicknames': ['Marrero']},
    {'realname': 'Alejo Ramos Padilla', 'nicknames': [
        'Ramos Padilla', 'Alejo Ramos Padilla', 'Padilla']},
    {'realname': 'Jorge Luis Llaven Abarca', 'nicknames': [
        'Llaven Abarca', 'Jorge Luis Llaven Abarca']},
    {'realname': 'LADY DIANA SALAZAR MÉNDEZ', 'nicknames': ['Diana Salazar']},
    {'realname': 'Humberto Saenz Marinero',
        'nicknames': ['Humberto Sáenz M']},
    {'realname': 'Sergio Tomás Massa', 'nicknames': ['Massa', 'Sergio Massa']},
    {'realname': 'Florencia Etcheves', 'nicknames': ['Etcheves']},
    {'realname': 'Musa Besaile',
        'nicknames': ['Musa Besaile', 'Besaile', 'Musa Abraham Besayle Fayad', 'Musa Abraham Besayle']},
    {'realname': 'Vereador Cadmiel Pereira', 'nicknames': ['Cadmiel Pereira']},
    {'realname': 'Thelma Esperanza Aldana Hernández',
        'nicknames': ['Thelma Aldana', 'Thelma']},
    {'realname': 'Néstor Humberto Martínez', 'nicknames': [
        'Néstor Humberto Martínez Neira', 'Nestor Humberto Martínez Neira', 'Fiscal Martínez',
        'Martínez', 'Fiscal', 'Néstor Humberto Martínez', 'Nestor Humberto', 'néstor h martinez']},
    {'realname': 'Rutilio Cruz Escandón Cadenas',
        'nicknames': ['Rutilio Escandón']},
    {'realname': 'Juan Eulogio Guerra Liera',
        'nicknames': ['Juan Eulogio Guerra Liera']},
    {'realname': 'Víctor Edmundo Caballero Durán',
        'nicknames': ['Victor Caballero']},
    {'realname': 'Jorge Homero Yunda Machado',
        'nicknames': ['jorge yunda (loro)', 'loro']},
    {'realname': 'Farik Karin Mora Salcedo', 'nicknames': [
        'Farik Karin Mora Salcedo', 'Farik Karin Mora Salcedo C.I']},
    {'realname': 'Juan Gomez Canessa', 'nicknames': ['Juan Ancap']},
    {'realname': 'Roberto Eugenio Marrero Borjas',
        'nicknames': ['Roberto Marrero']},
    {'realname': 'Julio Andrés Borges Junyent', 'nicknames': ['Julio Borges']},
    {'realname': 'Juan Carlos Requesens Martínez',
        'nicknames': ['Juan Requesens']},
    {'realname': 'Maricarmen Marín Salinas', 'nicknames': ['Mari Carmen']},
    {'realname': 'Consuelo Madrigal Martínez',
        'nicknames': ['Consuelo Madrigal']},
    {'realname': 'Vidulfo Rosales Sierra', 'nicknames': ['Vidulfo Rosales']},
    {'realname': 'Graciela Camaño', 'nicknames': ['Graciela Camaño']},
    {'realname': 'Grady Franklin', 'nicknames': ['Gray Tollison', 'Gray']},
    {'realname': 'Carlos Roberto Vielmann Montes',
        'nicknames': ['Roberto Vielmann']},
    {'realname': 'José del Regato Hoyo', 'nicknames': ['José Regato']},
    {'realname': 'Mauricio Macri', 'nicknames': ['Mauricio Macri', 'Macri']},
    {'realname': 'Germán Carlos Garavano', 'nicknames': ['Garavano']},
    {'realname': 'Conselho Fiscal', 'nicknames': ['Conselho Fiscal']},
    {'realname': 'Ana Vanessa Gutiérrez', 'nicknames': ['Vanessa Gutiérrez']},
    {'realname': 'Enrique Senestrari', 'nicknames': ['Enrique Senestrari']},
    {'realname': 'José Amalio Graterol',
        'nicknames': ['José AMALIO Graterol']},
    {'realname': 'Alicia Monroy Carmona',
        'nicknames': ['Alicia Monroy Carmona']},
    {'realname': 'Luisa Marvelia Ortega Díaz', 'nicknames': [
        'Luisa Ortega', 'Luisa Ortega Díaz', 'Luisa Ortega Díaz']},
    {'realname': 'Tarek William Saab Halabi', 'nicknames': [
        'Fiscal @TarekWiliamSaab', 'Tarek William Saab']},
    {'realname': 'Cristina Elisabet Fernández de Kirchner',
        'nicknames': ['Kirchner']},
    {'realname': 'Elizabeth Fuentes', 'nicknames': ['Elizabeth Fuentes']},
    {'realname': 'James Rodríguez',
        'nicknames': ['Rodríguez', 'James', 'El 10']},
    {'realname': 'Rafeal Vela Barba', 'nicknames': [
        'Rafeal Vela Barba', 'Rafeal']},
    {'realname': 'Stephen Moore', 'nicknames': ['Stephen Moore']},
    {'realname': 'Beatriz Acosta Medina', 'nicknames': ['Beatriz Acosta']},
    {'realname': 'Luis Fernando del Rincón',
        'nicknames': ['Fernando Del Rincon']},
    {'realname': 'Carlos Julián Bermeo Casas',
        'nicknames': ['Fiscal Carlos ']},
    {'realname': 'Norman Maurice Armitage Cadavid',
        'nicknames': ['Maurice Armitage', 'armitage', 'Maurice Armitage']},
    {'realname': 'Fatou Bom Bensouda', 'nicknames': ['Fatou Bensouda']},
    {'realname': 'MARIA VICTORIA MACHADO ANAYA',
        'nicknames': ['Victoria Machado']},
    {'realname': 'Alberto Manguel', 'nicknames': ['Manguel']},
    {'realname': 'Carlos Stornelli', 'nicknames': ['Fiscal Stornelli']},
    {'realname': 'Jorge Winckler Ortiz',
        'nicknames': ['Fiscal @AbogadoWinckler']},
    {'realname': 'Nicolás Lucca', 'nicknames': ['Nicolás Lucca']},
    {'realname': 'María Lourdes Afiuni Mora', 'nicknames': [
        'María Afiuni', 'María Lourdes Afiuni', 'lourdes afiuni']},
    {'realname': 'Jair Bolsonaro', 'nicknames': ['Bolsonaro']},
    {'realname': 'Vicky Dávila',
        'nicknames': ['Vicky Dávila', 'Vickisita', 'Vicky']},
    {'realname': 'Diosdado Cabello Rondón',
        'nicknames': ['Diosdado', 'Diosdado Cabello']},
    {'realname': 'Esteban Moctezuma Barragán',
        'nicknames': ['Esteban Moctezuma']},
    {'realname': 'Verónica Michelle Bachelet Jeria',
        'nicknames': ['Michelle Bachelet']},
    {'realname': 'Michel Miguel Elias Temer Lulia',
        'nicknames': ['Pdte Temer', 'Michel Temer']},
    {'realname': 'Rafael Vicente Correa Delgado',
        'nicknames': ['Rafael Correa', 'Correa']},
    {'realname': 'Napoleón Gómez Urrutia', 'nicknames': [
        'Napoleón Gómez Urrutia', 'Napoleón Urrutia']},
    {'realname': 'Olga María del Carmen Sánchez Cordero Dávila',
        'nicknames': ['Olga Sánchez']},
    {'realname': 'Martí Batres Guadarrama', 'nicknames': ['Martí Batres']},
    {'realname': 'Gustavo Gorriti Ellenbogen',
        'nicknames': ['Gustavo Gorriti']},
    {'realname': 'Enrique Peñalosa',
        'nicknames': ['Peñalosa', 'Enrique Peñalosa', 'Bobolitro']},
    {'realname': 'Omar Ángel Perotti', 'nicknames': ['Omar Perotti']},
    {'realname': 'Ricardo Alberto Lombana González',
        'nicknames': ['Ricardo Lombana']},
    {'realname': 'Antonio Bonfatti', 'nicknames': ['Antonio Bonfatti']},
    {'realname': 'Juan Manuel Sheput Moore', 'nicknames': ['Juan Sheput']},
    {'realname': 'Gisela Marziotta', 'nicknames': ['Marziotta']},
    {'realname': 'Nelsored González', 'nicknames': ['Nelsored González']},
    {'realname': 'Ronny Xavier Aleaga Santos',
        'nicknames': ['ASAMBLEISTA RONNY ALEAGA SANTOS']},
    {'realname': 'Joaquín Víctor González', 'nicknames': ['Jose B. Gonzalez']},
    {'realname': 'Mossack Fonseca & Co', 'nicknames': ['Mossack Fonseca']},
    {'realname': 'MintPress News', 'nicknames': ['MintPress News']},
    {'realname': 'Lenín Boltaire Moreno Garcés',
        'nicknames': ['Lenín Moreno']},
    {'realname': 'Rodrigo Lara Restrepo', 'nicknames': ['Lara']},
    {'realname': 'JORGE RENGIFO', 'nicknames': ['Don Corneliano']},
    {'realname': 'Elisa María Avelina Carrió',
        'nicknames': ['Elisa Lilita Carrió']},
    {'realname': 'William Henry Gates III', 'nicknames': ['Bill Gates']},
    {'realname': 'Ramses Owens', 'nicknames': ['Ramses Owens']},
    {'realname': 'Richard Gaffey', 'nicknames': ['Richard Gaffey']},
    {'realname': 'Dirk Brauer', 'nicknames': ['Dirk Brauer']},
    {'realname': 'Graciana Peñafort', 'nicknames': ['Graciana Peñafort']},
    {'realname': 'Maryam Nawaz Sharif', 'nicknames': ['Maryam Nawaz Sharif']},
    {'realname': 'Jorge Enrique Robledo',
        'nicknames': ['jorge Robledo', 'robledo']},
    {'realname': 'Hugo Gustavo Matteri',
        'nicknames': ['Hugo Matteri üå¥‚òÄüå¥']},
    {'realname': 'Marina Walker Guevara', 'nicknames': ['Marina Walker']},
    {'realname': 'Claudia López Hernández',
        'nicknames': ['Claudia López', 'López', 'lopez', 'claudia']},
    {'realname': 'Yidis Medina',
        'nicknames': ['Yidis', 'yidis medina']},
    {'realname': 'John David McAfee', 'nicknames': ['John McAfee Explains']},
    {'realname': 'José Gregorio Hernández Cisneros​​',
        'nicknames': ['José Gregorio Hdez G']},
    {'realname': 'Ana María Aristizábal', 'nicknames': ['ANA ARISTIZABAL']},
    {'realname': 'Miguel Uribe Turbay', 'nicknames': [
        'Miguel Uribe Turbay', 'Miguel Uribe']},
    {'realname': 'Maria Andrea Nieto Romero', 'nicknames': ['ANDREA NIETO']},
    {'realname': 'David Ricardo Racero Mayorca',
        'nicknames': ['David Racero üá®üá¥']},
    {'realname': 'Carlos Holmes Trujillo',
        'nicknames': ['Carlos Holmes Trujillo', 'Carlos Holmes', 'Holmes', 'Holmes trujillo']},
    {'realname': 'Iván Cepeda Castro', 'nicknames': [
        '@IvanCepedaCast', 'Iván Cepeda Castro', 'Cepeda', 'Ivan Cepeda', 'DR IVAN CEPEDA']},
    {'realname': 'Luis Fernando Velasco',
        'nicknames': ['LuisFernandoVelascoP']},
    {'realname': 'Maxine Moore Waters', 'nicknames': ['Maxine Waters']},
    {'realname': 'Steven Terner Mnuchin',
        'nicknames': ['Mnuchin Trump Taxes']},
    {'realname': 'Donald Trump', 'nicknames': [
        'Trumpo', 'Trump', 'presidente Trump']},
    {'realname': 'Harald Joachim von der Goltz',
        'nicknames': ['Harald Von Der Goltz']},
    {'realname': 'Heloisa Cruz', 'nicknames': ['Heloisa Cruz']},
    {'realname': 'Jovenel Moise', 'nicknames': ['Président Jovenel Moise']},
    {'realname': 'Alejandro Antonio Cortés Vilches',
        'nicknames': ['Alejandro Cortés']},
    {'realname': 'Santiago Moure',
        'nicknames': ['Santiago Moure', 'Moure']},
    {'realname': 'Sara Tufano', 'nicknames': ['Sara Tufano']},
    {'realname': 'Temístocles Ortega Narváez',
        'nicknames': ['TEMISTOCLES ORTEGA']},
    {'realname': 'María Isabel Rueda',
        'nicknames': ['María Isabel Rueda', 'isabel rueda']},
    {'realname': 'Luis Ernesto Gómez', 'nicknames': ['Sena @LuisErnestoGL']},
    {'realname': 'Victor Horacio Verbes', 'nicknames': ['Víctor Horacio']},
    {'realname': 'Hassan Nassar',
        'nicknames': ['Hassan Nassar', 'Nassar']},
    {'realname': 'Mario Uribe Escobar',
        'nicknames': ['Mario Uribe Escobar', 'Mario Uribe']},
    {'realname': 'Manuel Ignacio de Vivanco Iturralde',
        'nicknames': ['Vivanco']},
    {'realname': 'Jaime Garzón',
        'nicknames': ['Jaime Garzón']},
    {'realname': 'Manuel Uribe Ángel', 'nicknames': ['Manuel Uribe']},
    {'realname': 'Francisco Gento López', 'nicknames': ['Paco Gento']},
    {'realname': 'Robert Charlton', 'nicknames': ['Bobby Charlton']},
    {'realname': 'Diego Armando Maradona Franco', 'nicknames': ['Maradona']},
    {'realname': 'Óscar Iván Zuluaga',
        'nicknames': ['Óscar Iván Zuluaga', 'Zuluaga', 'Oscar Ivan', 'Óscar Iván', 'Óscar Iván Zuluaga', 'iván zuluaga']},
    {'realname': 'Paola Andrea Holguín Moreno', 'nicknames': [
        'Paola Holguín üá®üá¥', 'Paola Holguín', 'Paola Andrea Holguín', 'Paola Holguín']},
    {'realname': 'Ángela María Robledo',
        'nicknames': ['Ángela María Robledo', 'angela robledo', 'maria robledo']},
    {'realname': 'Antonio Navarro Wolff ', 'nicknames': [
        'Navarro Wolff', 'navarro', 'antonio navarro']},
    {'realname': 'Paloma Valencia',
        'nicknames': ['Senadora Paloma Valencia', 'paloma', 'paloma valencia']},
    {'realname': 'VICTORIA EUGENIA LOMBANA GOMEZ',
        'nicknames': ['Eugenia Lombana']},
    {'realname': 'Cristina Lombana Velásquez',
        'nicknames': ['Cristina Lombana']},
    {'realname': 'Maria Ovidia Palechor', 'nicknames': [
        'Indígena Maria Ovidia Palechor', 'Maria Ovidia Palechor']},
    {'realname': 'Andrés Danilo Rodríguez',
        'nicknames': ['Daniilo Rodríguez']},
    {'realname': 'María Antonia Pardo', 'nicknames': [
        'María Antonia Pardo', 'Maria Antonia Pardo']},
    {'realname': 'Darío de Jesús Monsalve Mejía',
        'nicknames': ['Dario Monsalve']},
    {'realname': 'Isaías Duarte Cancino',
        'nicknames': ['Isaias Duarte Cancino']},
    {'realname': 'Enrique Santiago Romero', 'nicknames': [
        'Enrique Santiago https://t.co/SRc60OYEls']},
    {'realname': 'Jesús Santrich', 'nicknames': [
        'Santrich', 'j santrich', 'jesus santrich']},
    {'realname': 'Iván Márquez', 'nicknames': [
        'i marquez', 'ivan marquez', 'Márquez']}
]

falses_entities = ['jorge', '29Cheva', '@WRadioColombiaC. Constitucional@JEP_ColombiaELNNacionalCorruptos', 'Abogado', 'Alcaldía MH', 'Andyüß∏', 'Angie Ô£ø', 'Armando.Info', 'BeGrand Vecinos', 'Cable', 'Calle', 'Camaléon', 'Colombianos', 'Cometeram', 'Congreso', 'Consejo', 'Corporación', 'Cuentas', 'Cámara', 'Derecho', 'Diario La Página', 'Directora', 'Días', 'Esas', 'Estado', 'Etcheves', 'Exijimos', 'Filoplanctón', 'GENUINA', 'Gastarse', 'Government Panama Papers Investigation', 'Gracias', 'Guardabosques', 'Hahahaha okay jep aku faham', 'Haja', 'Harald Von Der Goltz', 'Hpta', 'Impolutas', 'Inocentes', 'Investigan ADN', 'Izquierda', 'JB3Fu44nyt@CuartoDeHoraCol@elespectador', 'Jajajajaj', 'Juanchito', 'Justicia Ordinaria', 'Lalisü•ü', 'Lava Toga', 'Legal System', 'Leslie üåπ‚≠êÔ∏è‚úäüåà üåÖAlbyDIANCPI', 'Llaven Abarca', 'Luis', 'M8-EM8', 'MP de Guatemala', 'Magistrada', 'Manguel', 'Masas', 'Nacional',
                   'Nelsored González', 'Noruega produz com', 'Nous allons', 'O Antagonista', 'ODB', 'PPK', 'Paz', 'Pelotuda', 'Pequeños Santoros', 'Petro Summer Camp@rcnradioCRICGuerraHolaGerenteJEP', 'Pobres', 'Procedimientos', 'RPP', 'Ratas', 'Red Activismoüå≥', 'Rendición', 'SAC', 'Saab', 'Senado', 'Senador', 'Serpiente Vendepatria üá≥üáÆüáªüá™', 'Socia', 'Socio', 'Soros', 'Soy Ma', 'Tapenl', 'This is because the internet', 'Tintin_antiuribista', 'Uma', 'Uribe James l Diaz muriel radamel', 'Uribismo', 'VISTA A COLOMBIA üá®üá¥', 'Valla', 'Verdes', 'Victimas', 'abogado', 'abogado', 'anticorrupción', 'ataque', 'candidato', 'congresistas', 'cristiano', 'curúl', 'de la Paz', 'delito', 'experto', 'fox üçåüêü', 'guerra', 'hoy', 'if not bakit ka naghahanap #JustSaying', 'los', 'mais barata kkkkkkkk', 'mamertería', 'nem falo', 'pastor', 'periodista', 'presidenta', 'presidente', 'profesor', 'prostituta', 'río', 'último', ]
false_entities_pattern = ['.*http.*']
