final_entities = [
    {'realname': 'Ivan Duque', 'nicknames': ['Titere', 'Porky', 'Señor de los mandados de El Ubérrimo',
                                             'Mijito', 'Presidente Duque', 'Duque', 'Ivan', 'Ivan Duque Marquez', 'Iv√°n Duque']},
    {'realname': 'Alvaro Uribe Velez', 'nicknames': ['alvaro', 'El innombrable ', 'Patron', 'Presidente Uribe', 'URIBE', '√Ålvaro', 'Alvaro Uribe Velez', 'Senador Uribe',
                                                     'Alvaro Uribe V√©lez', '√Ålvaro Uribe', '√Ålvaro Uribe V√©lez @AlvaroUribeVel', '√Ålvaro Uribe V√©lez', 'Presidente Uribe', 'Alvaro Uribe', 'PARACO']},
    {'realname': 'Pablo Catatumbo', 'nicknames': ['Narcoterrorista']},
    {'realname': 'Antanas Mockus', 'nicknames': ['Profe', 'Mockus']},
    {'realname': 'Juan Manuel Santos ', 'nicknames': ['El culpable', 'Santos', 's√°trapa Santos',
                                                      'Juan Manuel Santos', 'Juan Manuel Santos @JuanManSantos', 'Juan Manuel', 'JuanMa', 'Chuki', 'Juanma', 'JU- HAMPA', 'Falso Nobel', 'presidente Santos', 'JM']},
    {'realname': 'Maria Margarita Zuleta', 'nicknames': ['La paca Zuleta']},
    {'realname': 'Federico Gutierrez ', 'nicknames': ['Uribista urasangres']},
    {'realname': 'Gustavo Francisco Petro Urrego', 'nicknames': [
        'Gaitanista', 'Gustavo Petro', 'PETRO', 'Petro Summer Camp', 'Terrorista M19', 'Petro']},
    {'realname': 'German Vargas Lleras', 'nicknames': [
        'Frentenacionalista', 'Vargas', 'Lleras']},
    {'realname': 'Humberto de la calle ', 'nicknames': [
        'Liberal Reformista', 'De la Calle']},
    {'realname': 'Sergio Fajardo Valderrama',
        'nicknames': ['Sergio Fajardo', 'Fajardo']},
    {'realname': 'María del Rosario Guerra',
        'nicknames': ['Charo Guerra', 'Rosario Guerra']},
    {'realname': 'Daniel Alfonso Coronell Castañeda', 'nicknames': [
        'Daniel Coronell', 'Coronell']},
    {'realname': 'César Augusto Gaviria Trujillo', 'nicknames': ['Gaviria']},
    {'realname': 'Pablo Felipe Robledo del Castillo',
        'nicknames': ['Felipe Robledo']},
    {'realname': 'Nicolás Maduro Moros',
        'nicknames': ['Maduro', 'Nicol√°s Maduro']},
    {'realname': 'Juan Gerardo Antonio Guaidó Márquez', 'nicknames': [
        'Guaido', 'Presidente Interino de Venezuela', 'Guaid√≥']},
    {'realname': 'Andrés Felipe Arias Leiva', 'nicknames': [
        'Andresito', 'Arias', 'Andr√©s Felipe Arias', 'Uribito']},
    {'realname': 'Hugo Rafael Chávez Frías',
        'nicknames': ['Chavez', 'Ch√°vez', 'Hugo Chavez']},
    {'realname': 'Ernesto Macías Tovar', 'nicknames': [
        'Macias', 'Mac√≠as', 'Ernesto Mac√≠as']},
    {'realname': 'Armando Alberto Benedetti Villaneda',
        'nicknames': ['Armando Benedetti', 'Benedetti']},
    {'realname': 'Daniel Samper Ospina', 'nicknames': ['Samper']},
    {'realname': 'Alejandro Ordóñez Maldonado', 'nicknames': ['Ordoñez']},
    {'realname': 'Claudia Gurisatti Barreto',
        'nicknames': ['La Guri', 'Gurisatti']},
    {'realname': 'Roy Leonardo Barreras Montealegre',
        'nicknames': ['Roy', 'Lagarto', 'Roy Barreras']},
    {'realname': 'Lorenzo Guillermo Botero Nieto',
        'nicknames': ['Guillermo Botero']},
    {'realname': 'Juanita María Goebertus Estrada',
        'nicknames': ['Sra Goebertus', 'Juanita Goebertus', 'Goebertus']},
    {'realname': 'Jorge Alejandro Castro Salazar',
        'nicknames': ['Jorge Castro']},
    {'realname': 'Gino Francisco Costa Santolalla',
        'nicknames': ['Gino Costa üáµüá™', 'Gino Costa']},
    {'realname': 'Marco Antonio Arana Zegarra', 'nicknames': [
        'Marco Arana', 'Marco Arana üáµüá™']},
    {'realname': 'Antonio del Cristo Guerra de la Espriella',
        'nicknames': ['Exsenador Antonio Guerra', 'Antonio Gerra']},
    {'realname': 'Yeni Vilcatoma de la Cruz', 'nicknames': ['Yeni Vilcatoma']},
    {'realname': 'Jorge Henrique Simões Barata',
        'nicknames': ['Jorge Barata']},
    {'realname': 'Marcelo Bahia Odebrecht',
        'nicknames': ['Marcelo Odebrecht']},
    {'realname': 'María del Rosario Guerra de La Espriella', 'nicknames': [
        'Mar√≠a del Rosario Guerra', 'Senadora Guerra', 'María del Rosario Guerra de La Espriella']},
    {'realname': 'Rosa María Bartra Barriga', 'nicknames': ['Rosa Bartra']},
    {'realname': 'Marta Peñafiel Portila', 'nicknames': ['martha pe√±afiel']},
    {'realname': 'Jorge Ramírez Gallego', 'nicknames': ['Jorge Ram√≠rez']},
    {'realname': 'Félix Manuel Moreno Caballero',
        'nicknames': ['Felix Moreno']},
    {'realname': 'Silvana Carrion Ordinola',
        'nicknames': ['Silvana Carri√≥n', 'Silvana Carrion']},
    {'realname': 'Luis Pérez de Acha', 'nicknames': ['P√©rez de Acha']},
    {'realname': 'Luisa Maldonado', 'nicknames': ['Luisa Maldonado']},
    {'realname': 'Corte Suprema de Justicia',
        'nicknames': ['Corte Suprema de Jus']},
    {'realname': 'Mávila Milagros Huertas Centurión',
        'nicknames': ['Mavila Huertas C']},
    {'realname': 'Pedro Gonzalo Chávarry Vallejos',
        'nicknames': ['Ch√°varry']},
    {'realname': 'César José Hinostroza Pariachi',
        'nicknames': ['Hinostroza']},
    {'realname': 'Omar Marcos Arteaga', 'nicknames': ['Omar Marcos']},
    {'realname': 'Martín Alberto Vizcarra Cornejo',
        'nicknames': ['Mart√≠n Vizcarra']},
    {'realname': 'Lourdes Luisa Carreño', 'nicknames': [
        'Lourdes Luisa Carre√±o', 'Lourdes Luisa Carre√±o carcelen']},
    {'realname': 'Gustavo Gorriti Ellenbogen',
        'nicknames': ['Gustavo Gorriti']},
    {'realname': 'Jorge Enrique Castro Muñoz', 'nicknames': ['Jorge Castro']},
    {'realname': 'Vladimiro Montesinos Torres', 'nicknames': ['Montesinos']},
    {'realname': 'Cesar Epitácio Maia', 'nicknames': ['C√©sar Maia']},
    {'realname': 'Rodrigo Felinto Ibarra Epitácio Maia',
        'nicknames': ['Rodrigo Maia']},
    {'realname': 'Allison Azevedo de Farias',
        'nicknames': ['Alysson Azevedo']},
    {'realname': 'Keiko Sofía Fujimori Higuchi​',
        'nicknames': ['Keiko Fujimori']},
    {'realname': 'Alberto Kenya Fujimori Fujimori',
        'nicknames': ['A. Fujimori', 'Fujimori']},
    {'realname': 'José Ángel Guerra', 'nicknames': ['Joselito Guerra']},
    {'realname': 'Marta Lucía Ramírez Blanco', 'nicknames': [
        'Marta Luc√≠a Ram√≠rez', 'uribista Mar√≠a', 'Mar√≠a', 'Martica', 'Marta Lucia']},
    {'realname': 'Fernando Londoño Hoyos', 'nicknames': [
        'Fernando Londo√±o Hoy', 'Fernando Invercolsa Hoyos', 'Fernando Londo√±o Hoyos', 'Londo√±o', 'Fernando Londo√±o', 'Fernando Londoño']},
    {'realname': 'Gustavo Adolfo Rugeles', 'nicknames': [
        'Gustavo Rugeles', 'Maltratador Gustavo Rugeles', 'Rugeles', 'maltratador rugeles']},
    {'realname': 'José Obdulio Gaviria',
        'nicknames': ['Jose Obtuso', 'Obdulio']},
    {'realname': 'Julián Román Rey', 'nicknames': ['Julian Roman']},
    {'realname': 'Aurelio Arturo Martínez', 'nicknames': ['Arturo M.']},
    {'realname': 'Salvatore Mancuso Gómez', 'nicknames': ['Mancuso']},
    {'realname': 'Carlos Castaño Gil', 'nicknames': [
        'Carlos Casta√±o', 'Carlos Castaño', 'castaño']},
    {'realname': 'Jorge Enrique Pizano', 'nicknames': ['Pizano']},
    {'realname': 'Ramiro Bejarano Guzmán',
        'nicknames': ['Ramiro Bejarano Guzm√°n', 'Ramiro Bejarano']},
    {'realname': 'Mariano Rajoy Brey',
        'nicknames': ['Rajoy', 'Mariano Rajoy']},
    {'realname': 'José Adrián Marrero Berrocal', 'nicknames': ['Marrero']},
    {'realname': 'Alejo Ramos Padilla', 'nicknames': [
        'Ramos Padilla', 'Alejo Ramos Padilla', 'Padilla']},
    {'realname': 'Jorge Luis Llaven Abarca', 'nicknames': [
        'Llaven Abarca', 'Jorge Luis Llaven Abarca']},
    {'realname': 'LADY DIANA SALAZAR MÉNDEZ', 'nicknames': ['Diana Salazar']},
    {'realname': 'Humberto Saenz Marinero',
        'nicknames': ['Humberto S√°enz M']},
    {'realname': 'Sergio Tomás Massa', 'nicknames': ['Massa', 'Sergio Massa']},
    {'realname': 'Florencia Etcheves', 'nicknames': ['Etcheves']},
    {'realname': 'Musa Abraham Besayle Fayad',
        'nicknames': ['Musa Besaile', 'Besaile']},
    {'realname': 'Vereador Cadmiel Pereira', 'nicknames': ['Cadmiel Pereira']},
    {'realname': 'Thelma Esperanza Aldana Hernández',
        'nicknames': ['Thelma Aldana', 'Thelma']},
    {'realname': 'Néstor Humberto Martínez Neira', 'nicknames': [
        'Nestor Humberto Mart√≠nez Neira', 'Fiscal Mart√≠nez', 'Mart√≠nez', 'Fiscal', 'N√©stor Humberto Mart√≠nez', 'Nestor Humberto']},
    {'realname': 'Sergio Andrés Vergara Sáez',
        'nicknames': ['Sergio Vergara', 'Vergara']},
    {'realname': 'Rutilio Cruz Escandón Cadenas',
        'nicknames': ['Rutilio Escand√≥n']},
    {'realname': 'Juan Eulogio Guerra Liera',
        'nicknames': ['Juan Eulogio Guerra Liera']},
    {'realname': 'Víctor Edmundo Caballero Durán',
        'nicknames': ['Victor Caballero']},
    {'realname': 'Jorge Homero Yunda Machado',
        'nicknames': ['jorge yunda (loro)', 'loro']},
    {'realname': 'Lic.Macoco', 'nicknames': ['Lic.Macoco']},
    {'realname': 'Ana María Raquel Verdesoto de Romo Dávila',
        'nicknames': ['Verdezoto']},
    {'realname': 'Farik Karin Mora Salcedo', 'nicknames': [
        'Farik Karin Mora Salcedo', 'Farik Karin Mora Salcedo C.I']},
    {'realname': 'Juan Gomez Canessa', 'nicknames': ['Juan Ancap']},
    {'realname': 'Roberto Eugenio Marrero Borjas',
        'nicknames': ['Roberto Marrero']},
    {'realname': 'Julio Andrés Borges Junyent', 'nicknames': ['Julio Borges']},
    {'realname': 'Juan Carlos Requesens Martínez',
        'nicknames': ['Juan Requesens']},
    {'realname': 'Maricarmen Marín Salinas', 'nicknames': ['Mari Carmen']},
    {'realname': 'Consuelo Madrigal Martínez',
        'nicknames': ['Consuelo Madrigal']},
    {'realname': 'Vidulfo Rosales Sierra', 'nicknames': ['Vidulfo Rosales']},
    {'realname': 'Graciela Camaño', 'nicknames': ['Graciela Cama√±o']},
    {'realname': 'Grady Franklin', 'nicknames': ['Gray Tollison', 'Gray']},
    {'realname': 'Carlos Roberto Vielmann Montes',
        'nicknames': ['Roberto Vielmann']},
    {'realname': 'José del Regato Hoyo', 'nicknames': ['Jos√© Regato']},
    {'realname': 'Mauricio Macri', 'nicknames': ['Mauricio Macri', 'Macri']},
    {'realname': 'Germán Carlos Garavano', 'nicknames': ['Garavano']},
    {'realname': 'Conselho Fiscal', 'nicknames': ['Conselho Fiscal']},
    {'realname': 'Ana Vanessa Gutiérrez', 'nicknames': ['Vanessa Guti√©rrez']},
    {'realname': 'Enrique Senestrari', 'nicknames': ['Enrique Senestrari']},
    {'realname': 'José Amalio Graterol',
        'nicknames': ['Jos√© AMALIO Graterol']},
    {'realname': 'Alicia Monroy Carmona',
        'nicknames': ['Alicia Monroy Carmona']},
    {'realname': 'Luisa Marvelia Ortega Díaz', 'nicknames': [
        'Luisa Ortega', 'Luisa Ortega D√¨az', 'Luisa Ortega D√≠az']},
    {'realname': 'André Martín Carrillo Díaz', 'nicknames': ['Carri√≥']},
    {'realname': 'Julián del Casal y de la Lastra', 'nicknames': ['Casal']},
    {'realname': 'Tarek William Saab Halabi', 'nicknames': [
        'Fiscal @TarekWiliamSaab', 'Tarek William Saab']},
    {'realname': 'Cristina Elisabet Fernández de Kirchner',
        'nicknames': ['Kirchner']},
    {'realname': 'Elizabeth Fuentes', 'nicknames': ['Elizabeth Fuentes']},
    {'realname': 'James David Rodríguez Rubio',
        'nicknames': ['Rodr√≠guez', 'James', 'El 10']},
    {'realname': 'Rafeal Vela Barba', 'nicknames': [
        'Rafeal Vela Barba', 'Rafeal']},
    {'realname': 'Stephen Moore', 'nicknames': ['Stephen Moore']},
    {'realname': 'Beatriz Acosta Medina', 'nicknames': ['Beatriz Acosta']},
    {'realname': 'Luis Fernando del Rincón',
        'nicknames': ['Fernando Del Rincon']},
    {'realname': 'Carlos Julián Bermeo Casas',
        'nicknames': ['Fiscal Carlos ']},
    {'realname': 'Norman Maurice Armitage Cadavid',
        'nicknames': ['Maurice Armitage']},
    {'realname': 'Fatou Bom Bensouda', 'nicknames': ['Fatou Bensouda']},
    {'realname': 'MARIA VICTORIA MACHADO ANAYA',
        'nicknames': ['Victoria Machado']},
    {'realname': 'Alberto Manguel', 'nicknames': ['Manguel']},
    {'realname': 'Carlos Stornelli', 'nicknames': ['Fiscal Stornelli']},
    {'realname': 'Jorge Winckler Ortiz',
        'nicknames': ['Fiscal @AbogadoWinckler']},
    {'realname': 'Nicolás Lucca', 'nicknames': ['Nicol√°s Lucca']},
    {'realname': 'María Lourdes Afiuni Mora', 'nicknames': [
        'Mar√≠a Afiuni', 'Mar√≠a Lourdes Afiuni', 'lourdes afiuni']},
    {'realname': 'Jair Messias Bolsonaro', 'nicknames': ['Bolsonaro']},
    {'realname': 'Victoria Eugenia Dávila Hoyos',
        'nicknames': ['Vicky D√°vila', 'Vickisita', 'Vicky']},
    {'realname': 'Diosdado Cabello Rondón',
        'nicknames': ['Diosdado', 'Diosdado Cabello']},
    {'realname': 'Esteban Moctezuma Barragán',
        'nicknames': ['Esteban Moctezuma']},
    {'realname': 'Verónica Michelle Bachelet Jeria',
        'nicknames': ['Michelle Bachelet']},
    {'realname': 'Michel Miguel Elias Temer Lulia',
        'nicknames': ['Pdte Temer', 'Michel Temer']},
    {'realname': 'Rafael Vicente Correa Delgado',
        'nicknames': ['Rafael Correa', 'Correa']},
    {'realname': 'Napoleón Gómez Urrutia', 'nicknames': [
        'Napole√≥n G√≥mez Urrutia', 'Napoleón Urrutia']},
    {'realname': 'Olga María del Carmen Sánchez Cordero Dávila',
        'nicknames': ['Olga S√°nchez']},
    {'realname': 'Martí Batres Guadarrama', 'nicknames': ['Mart√≠ Batres']},
    {'realname': 'Gustavo Gorriti Ellenbogen',
        'nicknames': ['Gustavo Gorriti']},
    {'realname': 'Enrique Peñalosa Londoño',
        'nicknames': ['Pe√±alosa', 'Enrique Pe√±alosa', 'Bobolitro']},
    {'realname': 'Omar Ángel Perotti', 'nicknames': ['Omar Perotti']},
    {'realname': 'Ricardo Alberto Lombana González',
        'nicknames': ['Ricardo Lombana']},
    {'realname': 'Antonio Bonfatti', 'nicknames': ['Antonio Bonfatti']},
    {'realname': 'Juan Manuel Sheput Moore', 'nicknames': ['Juan Sheput']},
    {'realname': 'Gisela Marziotta', 'nicknames': ['Marziotta']},
    {'realname': 'Nelsored González', 'nicknames': ['Nelsored Gonz√°lez']},
    {'realname': 'Ronny Xavier Aleaga Santos',
        'nicknames': ['ASAMBLE√çSTA RONNY ALEAGA SANTOS']},
    {'realname': 'Joaquín Víctor González', 'nicknames': ['Jose B. Gonzalez']},
    {'realname': 'Mossack Fonseca & Co', 'nicknames': ['Mossack Fonseca']},
    {'realname': 'MintPress News', 'nicknames': ['MintPress News']},
    {'realname': 'Lenín Boltaire Moreno Garcés',
        'nicknames': ['Len√≠n Moreno']},
    {'realname': 'Rodrigo Lara Bonilla', 'nicknames': ['Lara']},
    {'realname': 'JORGE RENGIFO', 'nicknames': ['Don Corneliano']},
    {'realname': 'Elisa María Avelina Carrió',
        'nicknames': ['Elisa Lilita Carri√≥']},
    {'realname': 'William Henry Gates III', 'nicknames': ['Bill Gates']},
    {'realname': 'Ramses Owens', 'nicknames': ['Ramses Owens']},
    {'realname': 'Richard Gaffey', 'nicknames': ['Richard Gaffey']},
    {'realname': 'Dirk Brauer', 'nicknames': ['Dirk Brauer']},
    {'realname': 'Graciana Peñafort', 'nicknames': ['Graciana Pe√±afort']},
    {'realname': 'Maryam Nawaz Sharif', 'nicknames': ['Maryam Nawaz Sharif']},
    {'realname': 'Jorge Enrique Robledo Castillo',
        'nicknames': ['jorge Robledo', 'robledo']},
    {'realname': 'Hugo Gustavo Matteri',
        'nicknames': ['Hugo Matteri üå¥‚òÄüå¥']},
    {'realname': 'Marina Walker Guevara', 'nicknames': ['Marina Walker']},
    {'realname': 'Claudia Nayibe López Hernández',
        'nicknames': ['Claudia L√≥pez', 'L√≥pez','lopez']},
    {'realname': 'Yidis Medina Padilla',
        'nicknames': ['Yidis', 'yidis medina']},
    {'realname': 'John David McAfee', 'nicknames': ['John McAfee Explains']},
    {'realname': 'José Gregorio Hernández Cisneros​​',
        'nicknames': ['Jos√© Gregorio Hdez G']},
    {'realname': 'Ana María Aristizábal', 'nicknames': ['ANA ARISTIZABAL']},
    {'realname': 'Miguel Uribe Turbay', 'nicknames': [
        'Miguel Uribe Turbay', 'Miguel Uribe']},
    {'realname': 'Maria Andrea Nieto Romero', 'nicknames': ['ANDREA NIETO']},
    {'realname': 'David Ricardo Racero Mayorca',
        'nicknames': ['David Racero üá®üá¥']},
    {'realname': 'Carlos Holmes Trujillo García',
        'nicknames': ['Carlos Holmes Trujillo', 'Carlos Holmes']},
    {'realname': 'Iván Cepeda Castro', 'nicknames': [
        '@IvanCepedaCast', 'Iv√°n Cepeda Castro', 'Cepeda', 'Ivan Cepeda', 'DR IVAN CEPEDA']},
    {'realname': 'Luis Fernando Velasco Chaves',
        'nicknames': ['LuisFernandoVelascoP']},
    {'realname': 'Maxine Moore Waters', 'nicknames': ['Maxine Waters']},
    {'realname': 'Steven Terner Mnuchin',
        'nicknames': ['Mnuchin Trump Taxes']},
    {'realname': 'Donald Trump', 'nicknames': [
        'Trumpo', 'Trump', 'presidente Trump']},
    {'realname': 'Harald Joachim von der Goltz',
        'nicknames': ['Harald Von Der Goltz']},
    {'realname': 'Heloisa Cruz', 'nicknames': ['Heloisa Cruz']},
    {'realname': 'Jovenel Moise', 'nicknames': ['Pr√©sident Jovenel Mo√Øse']},
    {'realname': 'Alejandro Antonio Cortés Vilches',
        'nicknames': ['Alejandro Cort√©s']},
    {'realname': 'Santiago José Moure Erazo',
        'nicknames': ['Santiago Moure', 'Moure']},
    {'realname': 'Sara Tufano', 'nicknames': ['Sara Tufano']},
    {'realname': 'Temístocles Ortega Narváez',
        'nicknames': ['TEMISTOCLES ORTEGA']},
    {'realname': 'María Isabel Rueda Serbousek',
        'nicknames': ['Mar√≠a Isabel Rueda', 'isabel rueda']},
    {'realname': 'Luis Ernesto Gómez', 'nicknames': ['Sena @LuisErnestoGL']},
    {'realname': 'Victor Horacio Verbes', 'nicknames': ['V√≠ctor Horacio']},
    {'realname': 'Hassan Amín Abdul Nassar Pérez',
        'nicknames': ['Hassan Nassar', 'Nassar']},
    {'realname': 'Mario de Jesús Uribe Escobar',
        'nicknames': ['Mario Uribe Escobar', 'Mario Uribe']},
    {'realname': 'Manuel Ignacio de Vivanco Iturralde',
        'nicknames': ['Vivanco']},
    {'realname': 'Jaime Hernando Garzón Forero',
        'nicknames': ['Jaime Garz√≥n']},
    {'realname': 'Manuel Uribe Ángel', 'nicknames': ['Manuel Uribe']},
    {'realname': 'Francisco Gento López', 'nicknames': ['Paco Gento']},
    {'realname': 'Robert Charlton', 'nicknames': ['Bobby Charlton']},
    {'realname': 'Diego Armando Maradona Franco', 'nicknames': ['Maradona']},
    {'realname': 'Óscar Iván Zuluaga Escobar',
        'nicknames': ['√ìscar Iv√°n Zuluaga', 'Zuluaga', 'Oscar Ivan', 'Óscar Iván', 'Óscar Iván Zuluaga']},
    {'realname': 'Paola Andrea Holguín Moreno', 'nicknames': [
        'Paola Holgu√≠n üá®üá¥', 'Paola Holgu√≠n', 'Paola Andrea Holguín', 'Paola Holguín']},
    {'realname': 'Ángela María Robledo Gómez',
        'nicknames': ['√Ångela Mar√≠a Robledo', 'angela robledo']},
    {'realname': 'Antonio José Navarro Wolff', 'nicknames': [
        'Navarro Wolff', 'navarro', 'antonio navarro']},
    {'realname': 'Paloma Susana Valencia Laserna',
        'nicknames': ['Senadora Paloma Valencia', 'paloma', 'paloma valencia']},
    {'realname': 'VICTORIA EUGENIA LOMBANA GOMEZ',
        'nicknames': ['Eugenia Lombana']},
    {'realname': 'Cristina Lombana Velásquez',
        'nicknames': ['Cristina Lombana']},
    {'realname': 'Maria Ovidia Palechor', 'nicknames': [
        'Ind√≠gena Maria Ovidia Palechor', 'Maria Ovidia Palechor']},
    {'realname': 'Andrés Danilo Rodríguez',
        'nicknames': ['Daniilo Rodr√≠guez']},
    {'realname': 'María Antonia Pardo', 'nicknames': [
        'Mar√≠a Antonia Pardo', 'Maria Antonia Pardo']},
    {'realname': 'Darío de Jesús Monsalve Mejí',
        'nicknames': ['Dario Monsalve']},
    {'realname': 'Isaías Duarte Cancino',
        'nicknames': ['Isaias Duarte Cancino']},
    {'realname': 'Enrique Santiago Romero', 'nicknames': [
        'Enrique Santiago https://t.co/SRc60OYEls']},
    {'realname': ' Jesús Santrich', 'nicknames': [
        'Santrich']}
]

falses_entities = ['jorge', '29Cheva', '@WRadioColombiaC. Constitucional@JEP_ColombiaELNNacionalCorruptos', 'Abogado', 'Alcald√≠a MH', 'Andyüß∏', 'Angie Ô£ø', 'Armando.Info', 'BeGrand Vecinos', 'Cable', 'Calle', 'Camal√©on', 'Colombianos', 'Cometeram', 'Congreso', 'Consejo', 'Corporación', 'Cuentas', 'Cámara', 'Derecho', 'Diario La P√°gina', 'Directora', 'Días', 'Esas', 'Estado', 'Etcheves', 'Exijimos', 'Filoplanct√≥n', 'GENUINA', 'Gastarse', 'Government Panama Papers Investigation', 'Gracias', 'Guardabosques', 'Hahahaha okay jep aku faham', 'Haja', 'Harald Von Der Goltz', 'Hpta', 'Impolutas', 'Inocentes', 'Investigan ADN', 'Izquierda', 'JB3Fu44nyt@CuartoDeHoraCol@elespectador', 'Jajajajaj', 'Juanchito', 'Justicia Ordinaria', 'Lalisü•ü', 'Lava Toga', 'Legal System', 'Leslie üåπ‚≠êÔ∏è‚úäüåà üåÖAlbyDIANCPI', 'Llaven Abarca', 'Luis', 'M8-EM8', 'MP de Guatemala', 'Magistrada', 'Manguel', 'Masas', 'Nacional',
                   'Nelsored Gonz√°lez', 'Noruega produz com', 'Nous allons', 'O Antagonista', 'ODB', 'PPK', 'Paz', 'Pelotuda', 'Peque√±os Santoros', 'Petro Summer Camp@rcnradioCRICGuerraHolaGerenteJEP', 'Pobres', 'Procedimientos', 'RPP', 'Ratas', 'Red Activismoüå≥', 'Rendición', 'SAC', 'Saab', 'Senado', 'Senador', 'Serpiente Vendepatria üá≥üáÆüáªüá™', 'Socia', 'Socio', 'Soros', 'Soy Ma', 'Tapenl', 'This is because the internet', 'Tintin_antiuribista', 'Uma', 'Uribe James l Diaz muriel radamel', 'Uribismo', 'VISTA A COLOMBIA üá®üá¥', 'Valla', 'Verdes', 'Victimas', 'abogado', 'abogado', 'anticorrupción', 'ataque', 'candidato', 'congresistas', 'cristiano', 'curúl', 'de la Paz', 'delito', 'experto', 'fox üçåüêü', 'guerra', 'hoy', 'if not bakit ka naghahanap #JustSaying', 'los', 'mais barata kkkkkkkk', 'mamerter√≠a', 'nem falo', 'pastor', 'periodista', 'presidenta', 'presidente', 'profesor', 'prostituta', 'río', 'último', ]
false_entities_pattern = ['http']
